#include=/home/xicosantos/dotfiles/fuzzel/.config/fuzzel/catppuccin-frappe/


font=FiraCode Nerd Font
terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here

# output=<not set>
# dpi-aware=auto
# use-bold=no
# prompt="> "
# placeholder=
# icon-theme=default
# icons-enabled=yes
# hide-before-typing=no
# fields=filename,name,generic
# password-character=*
# filter-desktop=no
# match-mode=fzf
# sort-result=yes
# match-counter=no
# delayed-filter-ms=300
# delayed-filter-limit=20000
# show-actions=no
# launch-prefix=<not set>
# list-executables-in-path=no

# anchor=center
# x-margin=0
# y-margin=0
# lines=15
# width=30
# tabs=8
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0

# scaling-filter=box
# image-size-ratio=0.5

# gamma-correct-blending=no
# line-height=<use font metrics>
# letter-spacing=0

# layer=overlay
# keyboard-focus=exclusive
# exit-on-keyboard-focus-loss=yes

[colors]
background=eff1f5dd
text=4c4f69ff
prompt=5c5f77ff
placeholder=8c8fa1ff
input=4c4f69ff
match=1e66f5ff
selection=acb0beff
selection-text=4c4f69ff
selection-match=1e66f5ff
counter=8c8fa1ff
border=1e66f5ff

[border]
width=2
radius=10
